server:
  port: 0

spring:
  application:
    name: product

  datasource:
    url: jdbc:mysql://localhost:3306/product_kafka_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka