spring:
  application:
    name: inventory

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_kafka_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always