server:
  port: 0

spring:
  application:
    name: inventory

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_kafka_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inventory
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "*"
    template:
      default-topic: order_default_topic

eureka:
  client:
    service-url:
      defaultZone: http://<eureka-server>:<port>/eureka/