server:
  port: 8081

spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://localhost:3306/order_kafka_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always