server:
  port: 0

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        # Inventory Service Route
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/api/v1/item/**

        # Product Service Route
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO